# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install @oaphi/distributor
      run: |
        npm i chalk@^4.0.0 lodash@^4.17.15 yargs@^15.3.1
        echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} > .npmrc
        npm i @oaphi/distributor --registry="https://npm.pkg.github.com"
        unlink .npmrc

    - uses: actions/checkout@v2

    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  
  dist:
    
    runs-on: ubuntu-latest
    
    needs: [build]
    
    steps:
      - name: Creating dist file
        run: npm run dist
